apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: redis-master 
  labels: 
    app: redis 
spec:
  replicas: 1       
  selector:
    matchLabels: 
      app: redis 
      role: master 
      tier: backend     
  template: 
    metadata: 
      labels: 
        app: redis 
        role: master 
        tier: backend 
    spec: 
      containers: 
        - name: redis-master 
          image: redis:latest 
          ports: 
            - containerPort: 6379 
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: redis-master-svc 
  labels: 
    app: redis 
spec: 
  selector: 
    app: redis 
    role: master 
    tier: backend 
  ports: 
    - port: 6379 
       

