apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: redis-slave 
  labels: 
    app: redis 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: redis 
      role: slave 
      tier: backend 
  template: 
    metadata: 
      labels: 
        app: redis 
        role: slave 
        tier: backend 
    spec: 
      containers: 
        - name: redis-slave 
          image: gcr.io/google_samples/gb-redisslave:v3
          ports: 
            - containerPort: 6397 
          env: 
            - name: GET_HOSTS_FROM 
              value: dns 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: redis-slave-svc 
  labels: 
    app: redis 
spec: 
  type: NodePort 
  selector: 
    app: redis 
    role: slave 
    tier: backend
  ports: 
    - port: 6397 
      targetPort: 6397 
      nodePort: 32022
